# Generated by Django 4.1.4 on 2022-12-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=7)),
                ('givenName', models.CharField(max_length=25)),
                ('middleInitial', models.CharField(max_length=1)),
                ('surname', models.CharField(max_length=25)),
                ('birthday', models.DateTimeField(max_length=25)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.city')),
            ],
        ),
    ]
